namespace StatefulClanker.Tray;

sealed record InferencePreset(
    string Id,
    string DisplayName,
    string BaseUrlTemplate,
    string ModelsPathTemplate,
    string DiscoveryKind,
    bool RequiresAccountId,
    bool RequiresApiKey,
    string FreeLabel,
    string KeyPlaceholder,
    string SetupUrl,
    string Instructions,
    // Wire protocol this connection speaks. "openai-chat" (default) covers every
    // OpenAI-compatible gateway below. "anthropic-messages" is Anthropic's native
    // Messages API -- different auth header, different request/response shape --
    // the PowerShell worker runtime (lib/StatefulClanker.WorkerRuntime.ps1)
    // translates this project's canonical OpenAI-shaped message history to/from
    // it automatically, so nothing above the connection layer needs to know.
    string Protocol = "openai-chat",
    // Headers a connection using this preset should start with (e.g. Anthropic's
    // required anthropic-version), seeded into the Headers field on preset select.
    string DefaultHeaders = "",
    // True only for sources where automatically seeding zero-cost/local workhorse
    // candidates is a reasonable default. Mixed paid/free gateways stay false and
    // rely on per-model metadata or Clanker research instead.
    bool FreePoolProvider = false,
    // Authentication belongs to the provider adapter, not the user. The UI asks
    // only for the credential/identifier values; presets own header mechanics.
    // Supported values: bearer, x-api-key, none.
    string AuthKind = "bearer",
    // Provenance for maintenance: these presets are intentionally pillaged from
    // the provider catalogs maintained by FreeLLMAPI and 9Router.
    string Provenance = "StatefulClanker");

static class InferencePresets
{
    public static readonly InferencePreset[] All =
    {
        new("openrouter","OpenRouter","https://openrouter.ai/api/v1","/models","openai",false,true,
            "Ongoing free-model pool","sk-or-v1-...","https://openrouter.ai/settings/keys",
            "Create an OpenRouter account, open Settings > Keys, create a key, and paste it here. OpenRouter publishes free model variants and the openrouter/free router; model availability changes, so StatefulClanker discovers the live catalog instead of shipping a fixed list.", FreePoolProvider:true, Provenance:"FreeLLMAPI + 9Router"),
        new("anthropic","Anthropic","https://api.anthropic.com","/v1/models","openai",false,true,
            "No ongoing free tier; pay-as-you-go (new accounts may get limited trial credit)","sk-ant-...","https://console.anthropic.com/settings/keys",
            "Create an Anthropic account, open Console > API Keys, create a key, and paste it here. This preset uses Anthropic's native Messages API (x-api-key authentication and the anthropic-version header, not OpenAI-style Bearer tokens) -- StatefulClanker translates the worker/critic/validator tool-calling loop to and from Anthropic's wire format automatically, so it's used exactly like any other endpoint once saved.",
            "anthropic-messages","anthropic-version: 2023-06-01",AuthKind:"x-api-key"),
        new("groq","GroqCloud","https://api.groq.com/openai/v1","/models","openai",false,true,
            "Free rate-limited developer access","gsk_...","https://console.groq.com/keys",
            "Create a GroqCloud account, create an API key in the Groq console, and paste it here. The free developer limits vary by model and are returned/enforced by Groq.", FreePoolProvider:true, Provenance:"FreeLLMAPI + 9Router"),
        new("gemini","Google Gemini API / AI Studio","https://generativelanguage.googleapis.com/v1beta","/models","gemini",false,true,
            "Gemini API free tier","AQ... / AI Studio key","https://aistudio.google.com/apikey",
            "Open Google AI Studio, create a Gemini API key, and paste it here. StatefulClanker uses Google's native Gemini REST API with x-goog-api-key authentication, not the beta OpenAI compatibility gateway. This also avoids the Bearer-vs-AQ key ambiguity during Google's 2026 auth-key migration.",
            "gemini-native","x-goog-api-client: statefulclanker/0.8",FreePoolProvider:true,AuthKind:"x-goog-api-key",Provenance:"FreeLLMAPI + 9Router"),
        new("cloudflare","Cloudflare Workers AI","https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1","https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/models/search?format=openrouter&per_page=1000","cloudflare",true,true,
            "10,000 neurons/day free allocation","Cloudflare API token","https://dash.cloudflare.com/",
            "In the Cloudflare dashboard open Workers AI > Use REST API. Copy the Account ID and create a Workers AI API token with Workers AI Read/Edit permission. Enter both below. The free allocation resets daily.", FreePoolProvider:true, Provenance:"FreeLLMAPI + 9Router"),
        new("mistral","Mistral La Plateforme","https://api.mistral.ai/v1","/models","openai",false,true,
            "Free mode included usage; Labs models may be $0","MISTRAL_API_KEY","https://console.mistral.ai/api-keys",
            "Create a Mistral account, enable Free mode, create an API key, and paste it here. Current included usage is account-specific; Labs models marked free by Mistral can also be selected.", FreePoolProvider:true, Provenance:"FreeLLMAPI + 9Router"),
        new("huggingface","Hugging Face Inference Providers","https://router.huggingface.co/v1","/models","openai",false,true,
            "Small monthly free inference credit","hf_...","https://huggingface.co/settings/tokens",
            "Create a fine-grained Hugging Face token with permission to make calls to Inference Providers. Free accounts currently receive a small monthly inference credit. The catalog may route one model through several underlying providers.", FreePoolProvider:true, Provenance:"FreeLLMAPI + 9Router"),
        new("nvidia","NVIDIA NIM / build.nvidia.com","https://integrate.api.nvidia.com/v1","/models","openai",false,true,
            "Hosted Free Endpoint / API Catalog trial capacity","nvapi-...","https://build.nvidia.com/",
            "Join the NVIDIA Developer Program, open a model on build.nvidia.com, choose Prototype / API, and generate an API key. StatefulClanker can harvest the configured hosted catalog as trial/free-endpoint capacity. NVIDIA labels these hosted endpoints for trial/evaluation use, so the router records them separately from ordinary ongoing free production capacity.", FreePoolProvider:true, Provenance:"FreeLLMAPI + 9Router"),
        new("cohere","Cohere","https://api.cohere.ai/compatibility/v1","https://api.cohere.com/v1/models?page_size=1000&endpoint=chat","cohere",false,true,
            "Free evaluation key: 1,000 calls/month","Cohere API key","https://dashboard.cohere.com/api-keys",
            "Create a Cohere trial/evaluation API key and paste it here. Evaluation keys are free but limited and are not intended as production capacity. StatefulClanker uses Cohere's OpenAI Compatibility API for chat and the native model catalog for discovery."),
        new("kilo","Kilo AI Gateway","https://api.kilo.ai/api/gateway","/models","openai",false,false,
            "Free models; anonymous access up to 200 requests/hour/IP","","https://kilo.ai/docs/gateway",
            "No key is required for Kilo's free models. Select the preset and Test & discover immediately. You may optionally add a Kilo API key for account-backed access. Choose models tagged :free or kilo-auto/free; free requests are rate-limited by IP and some upstreams may log prompts.", FreePoolProvider:true, Provenance:"FreeLLMAPI + 9Router"),
        new("vercel","Vercel AI Gateway","https://ai-gateway.vercel.sh/v1","/models","openai",false,true,
            "$5/month included gateway credit while on the free tier","Vercel AI Gateway key","https://vercel.com/ai-gateway",
            "Create a Vercel account and an AI Gateway API key, then paste it here. Vercel currently includes $5/month of AI Gateway credit on the free tier; purchasing gateway credits moves the account to paid-tier billing and ends that monthly free credit."),
        new("cerebras","Cerebras Inference","https://api.cerebras.ai/v1","/models","openai",false,true,
            "$5 free trial credit (not ongoing free tier)","csk-...","https://cloud.cerebras.ai/",
            "Create a Cerebras Inference account and API key. Cerebras currently advertises $5 of free trial credit; StatefulClanker labels this as trial rather than ongoing free inference."),
        new("ollama","Ollama (local)","http://127.0.0.1:11434/v1","/models","openai",false,false,
            "Free local inference","","https://ollama.com/",
            "Install Ollama and pull at least one model. Leave the API key blank. StatefulClanker connects to the local OpenAI-compatible endpoint and discovers installed models."),
        new("freellmapi","FreeLLMAPI gateway","http://127.0.0.1:3001/v1","/models","openai",false,true,
            "Unified pool of free-provider capacity","freellmapi-...","https://github.com/tashfeenahmed/freellmapi",
            "Install/run FreeLLMAPI, add whatever upstream free-provider credentials you want there, then copy its unified API key from the Keys page. StatefulClanker discovers FreeLLMAPI's live /v1/models catalog and treats it as one connection; FreeLLMAPI owns its provider quirks, quotas and internal failover.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI"),
        new("9router","9Router gateway","http://127.0.0.1:20128/v1","/models","openai",false,true,
            "Gateway over 9Router's configured provider/account pool","9Router API key","https://github.com/decolua/9router",
            "Run 9Router, configure provider accounts in its dashboard, and copy the gateway API key. StatefulClanker talks only to 9Router's OpenAI-compatible /v1 surface; 9Router keeps responsibility for OAuth/cookie/provider-specific transports and account rotation.",
            Provenance:"9Router"),
        new("github-models","GitHub Models (retired)","https://models.github.ai/inference","/models","openai",false,true,
            "RETIRED July 30, 2026","github_pat_...","https://docs.github.com/en/github-models",
            "GitHub fully retired the GitHub Models playground, catalog, inference API, and BYOK service on July 30, 2026. This preset remains visible only so existing saved connections are understandable and removable; do not add it as capacity.",
            FreePoolProvider:false,Provenance:"StatefulClanker"),
        new("zhipu","Z.ai / Zhipu","https://open.bigmodel.cn/api/paas/v4","/models","openai",false,true,
            "Free/low-cost GLM availability varies by account/model","Zhipu API key","https://open.bigmodel.cn/usercenter/apikeys",
            "Create a Z.ai/Zhipu API key and test the live model catalog. Prefer currently free Flash-class models for the workhorse pool.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI + 9Router"),
        new("ollama-cloud","Ollama Cloud","https://ollama.com/v1","/models","openai",false,true,
            "Recurring free cloud plan with model/session limits","Ollama API key","https://ollama.com/settings/keys",
            "Create an Ollama Cloud key. The free plan exposes a changing subset of the cloud catalog, so Test & refresh before targeting models.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI + 9Router"),
        new("pollinations","Pollinations","https://gen.pollinations.ai/v1","https://gen.pollinations.ai/text/models","openai",false,true,
            "Account-backed pollen budget; live text catalog includes pricing/capabilities","sk_...","https://enter.pollinations.ai",
            "Create a Pollinations secret key and paste it here. StatefulClanker uses the rich public /text/models catalog for live pricing/capabilities and /account/key for remaining key budget without inference. Only models that the live catalog actually proves zero-cost can enter the automatic $0 pool; HTTP 402 is treated as exhausted budget rather than a bad credential.",
            Provenance:"FreeLLMAPI"),
        new("llm7","LLM7","https://api.llm7.io/v1","/models","openai",false,false,
            "Anonymous/basic free models; optional key improves access","","https://llm7.io",
            "LLM7 exposes an OpenAI-compatible model catalog and free basic access. Add a key if your account provides one; otherwise test anonymously.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI + 9Router"),
        new("opencode-zen","OpenCode Zen","https://opencode.ai/zen/v1","/models","openai",false,true,
            "Promotional/free model roster changes over time","OpenCode key","https://opencode.ai/auth",
            "Create an OpenCode account key and discover the current Zen catalog. StatefulClanker supplies the required per-project x-opencode-session header automatically.",
            DefaultHeaders:"x-opencode-session: project",FreePoolProvider:true,Provenance:"FreeLLMAPI"),
        new("ovh","OVHcloud AI Endpoints","https://oai.endpoints.kepler.ai.cloud.ovh.net/v1","/models","openai",false,false,
            "Anonymous free inference is available on selected models","","https://endpoints.ai.cloud.ovh.net",
            "Test anonymously first. OVH also supports authenticated higher limits, but the no-card anonymous path is useful for the free workhorse pool.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI"),
        new("agnes","Agnes AI","https://apihub.agnes-ai.com/v1","/models","openai",false,true,
            "Promotional $0/token models; verify current catalog","Agnes API key","https://platform.agnes-ai.com",
            "Create a key and discover the live catalog. Treat zero-cost status as time-sensitive and record a research date when Clanker keeps a model in the target pool.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI"),
        new("reka","Reka","https://api.reka.ai/v1","/models","openai",false,true,
            "Recurring account credit/free allocation varies","Reka API key","https://platform.reka.ai",
            "Create a Reka key and discover the current OpenAI-compatible model list. Flash/Edge-class models are suitable candidates when their free allocation is active.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI"),
        new("siliconflow","SiliconFlow","https://api.siliconflow.com/v1","/models","openai",false,true,
            "Free models/credits vary by catalog","SiliconFlow API key","https://siliconflow.com",
            "Create a SiliconFlow key and discover the live model list. The service also exposes media models; StatefulClanker's workhorse filter excludes non-chat model families.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI + 9Router"),
        new("routeway","Routeway","https://api.routeway.ai/v1","/models","openai",false,true,
            "Free :free model routes","Routeway API key","https://routeway.ai",
            "Create a free key. StatefulClanker supplies a browser-compatible User-Agent automatically for Routeway's Cloudflare edge.",
            DefaultHeaders:"User-Agent: Mozilla/5.0 StatefulClanker",FreePoolProvider:true,Provenance:"FreeLLMAPI"),
        new("bazaarlink","BazaarLink","https://bazaarlink.ai/api/v1","/models","openai",false,true,
            "auto:free route and changing free catalog","BazaarLink API key","https://bazaarlink.ai",
            "Create a key and discover the current catalog. The auto:free route is intentionally useful when named direct models are paid.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI + 9Router"),
        new("ainative","AINative Studio","https://api.ainative.studio/api/v1","/models","openai",false,true,
            "Advertised recurring free allocation; verify account limits","AINative API key","https://ainative.studio",
            "Create a key and verify the current free allocation/model list before relying on it for unattended work.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI"),
        new("aion","Aion Labs","https://api.aionlabs.ai/v1","/models","openai",false,true,
            "Free aggregator tier; catalog changes","Aion API key","https://aionlabs.ai",
            "Create a key and discover the current OpenAI-compatible catalog. Keep free status dated in the target-pool rationale.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI"),
        new("requesty","Requesty","https://router.requesty.ai/v1","/models","openai",false,true,
            "Free router tier/models vary","Requesty API key","https://requesty.ai",
            "Create a Requesty key and discover the current catalog. Prefer explicitly zero-cost routes for automatic workhorse targeting.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI"),
        new("navy","NavyAI","https://api.navy/v1","/models","openai",false,true,
            "Free daily-token allocation","NavyAI API key","https://api.navy",
            "Create a key and discover the catalog. StatefulClanker supplies NavyAI's required-compatible User-Agent automatically.",
            DefaultHeaders:"User-Agent: FreeLLMAPI/1.0",FreePoolProvider:true,Provenance:"FreeLLMAPI"),
        new("nara","NaraRouter","https://router.bynara.id/v1","/models","openai",false,true,
            "Free plan after account/community verification","NaraRouter API key","https://router.bynara.id",
            "Create and verify a NaraRouter account, then discover which models currently answer on the free plan.",
            FreePoolProvider:true,Provenance:"FreeLLMAPI"),
        new("deepseek","DeepSeek","https://api.deepseek.com","/models","openai",false,true,
            "Usually paid; useful direct provider preset","DeepSeek API key","https://platform.deepseek.com/api_keys",
            "Create a DeepSeek API key. This direct preset is included because 9Router supports it; it is not automatically seeded into the free workhorse pool.",
            Provenance:"9Router"),
        new("fireworks","Fireworks AI","https://api.fireworks.ai/inference/v1","/models","openai",false,true,
            "Account/trial pricing varies","Fireworks API key","https://fireworks.ai/account/api-keys",
            "Create a Fireworks API key and discover the current LLM catalog.",
            Provenance:"9Router"),
        new("hyperbolic","Hyperbolic","https://api.hyperbolic.xyz/v1","/models","openai",false,true,
            "Account/trial pricing varies","Hyperbolic API key","https://app.hyperbolic.xyz",
            "Create a Hyperbolic API key and discover the current OpenAI-compatible catalog.",
            Provenance:"9Router"),
        new("chutes","Chutes AI","https://llm.chutes.ai/v1","/models","openai",false,true,
            "Requires usable account balance/quota","Chutes API key","https://chutes.ai/app/api",
            "Create a Chutes API key and discover the LLM catalog. Do not auto-classify it as free merely because individual community chutes may be inexpensive.",
            Provenance:"9Router"),
        new("nebius","Nebius AI Studio","https://api.studio.nebius.ai/v1","/models","openai",false,true,
            "Account/trial pricing varies","Nebius API key","https://studio.nebius.com/settings/api-keys",
            "Create a Nebius AI Studio key and discover the current model catalog.",
            Provenance:"9Router"),
        new("sambanova","SambaNova","https://api.sambanova.ai/v1","/models","openai",false,true,
            "Trial/paid access; old always-free tier is gone","SambaNova API key","https://cloud.sambanova.ai",
            "Create a SambaNova key and discover the current models. Kept as a connection preset because 9Router supports it, but it is not auto-targeted as free.",
            Provenance:"9Router"),
        new("together","Together AI","https://api.together.xyz/v1","/models","openai",false,true,
            "Account/trial pricing varies","Together API key","https://api.together.ai/settings/api-keys",
            "Create a Together API key and discover the current catalog.",
            Provenance:"9Router"),
        new("venice","Venice AI","https://api.venice.ai/api/v1","/models","openai",false,true,
            "Account pricing varies","Venice API key","https://venice.ai/settings/api",
            "Create a Venice API key and discover the current chat catalog. Media models returned by the service are excluded from automatic workhorse selection.",
            Provenance:"9Router"),
        new("api-airforce","API.airforce","https://api.airforce/v1","/models","openai",false,true,
            "Free-tier routes are provider-defined","API.airforce key","https://api.airforce",
            "Create/configure an API.airforce key and discover the current catalog.",
            FreePoolProvider:true,Provenance:"9Router"),
        new("baidu","Baidu Qianfan","https://qianfan.baidubce.com/v2","/models","openai",false,true,
            "Account pricing/free quota varies","Baidu API key","https://console.bce.baidu.com/qianfan/",
            "Create a Qianfan API key and discover the current OpenAI-compatible model catalog.",
            Provenance:"9Router"),
        new("tencent","Tencent Hunyuan","https://api.hunyuan.cloud.tencent.com/v1","/models","openai",false,true,
            "Account pricing/free quota varies","Tencent API key","https://console.cloud.tencent.com/hunyuan/api-key",
            "Create a Hunyuan API key and discover the current OpenAI-compatible model catalog.",
            Provenance:"9Router"),
        new("lmstudio","LM Studio (local)","http://127.0.0.1:1234/v1","/models","openai",false,false,
            "Free local inference","","https://lmstudio.ai/",
            "Install LM Studio, download a model, and start the Local Server with its OpenAI-compatible API enabled. Leave the API key blank."),
        new("vllm","vLLM (local / LAN)","http://127.0.0.1:8000/v1","/models","openai",false,false,
            "Free self-hosted inference","","https://docs.vllm.ai/",
            "Start vLLM's OpenAI-compatible server and enter its reachable base URL. If you configured API-key authentication, provide that key; otherwise leave it blank."),
        new("custom","Custom OpenAI-compatible","https://","/models","openai",false,false,
            "Depends on service","","",
            "Enter an OpenAI-compatible base URL. StatefulClanker will authenticate if a key is supplied, call the model-list endpoint, and only save the connection after a successful discovery.")
    };

    public static InferencePreset Get(string? id) =>
        All.FirstOrDefault(x => string.Equals(x.Id,id,StringComparison.OrdinalIgnoreCase)) ?? All[^1];

    public static string Expand(string template,string? accountId) =>
        template.Replace("{accountId}", accountId?.Trim() ?? "", StringComparison.OrdinalIgnoreCase);
}
